# Generated by Django 5.2.15 on 2026-06-09 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'квиз',
                'verbose_name_plural': 'квизы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='текст вопроса')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='описание')),
                ('options', models.JSONField(verbose_name='варианты ответа')),
                ('correct_answer', models.CharField(max_length=500, verbose_name='правильный ответ')),
                ('explanation', models.CharField(blank=True, default='', max_length=250, verbose_name='объяснение ответа')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=6, verbose_name='сложность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.category', verbose_name='категория')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='квиз')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
    ]
